blog/urls.py
from django.conf.urls import url
from blog.views import (IndexView, ArticleView, AllView, SearchView,
                        ColumnView, UserView, NewsView, TagView, CategoryView)
from django.views.generic import TemplateView, DetailView
from blog.models import News

urlpatterns = [
        url(r'^$', IndexView.as_view(), name='index-view'),
        url(r'^article/(?P<slug>\w+).html$',
            ArticleView.as_view(), name='article-detail-view'),
        url(r'^all/$', AllView.as_view(), name='all-view'),
        url(r'^search/$', SearchView.as_view()),
        url(r'^login/$',
            TemplateView.as_view(template_name="blog/login.html"),
            name='login-view'),
        url(r'^register/$',
            TemplateView.as_view(template_name="blog/register.html"),
            name='register-view'),
        url(r'^forgetpassword/$',
            TemplateView.as_view(template_name="blog/forgetpassword.html"),
            name='forgetpassword-view'),
        url(r'^resetpassword/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
            TemplateView.as_view(template_name="blog/resetpassword.html"),
            name='resetpassword-view'),
        url(r'^column/(?P<column>\w+)/$',
            ColumnView.as_view(), name='column-detail-view'),
        url(r'^user/(?P<slug>\w+)$', UserView.as_view(), name='user-view'),
        url(r'^news/$', NewsView.as_view(), name='news-view'),
        url(r'^news/(?P<pk>\w+)$',
            DetailView.as_view(model=News), name='news-detail-view'),
        url(r'^tag/(?P<tag>\w+)/$', TagView.as_view(), name='tag-detail-view'),
        url(r'^category/(?P<category>\w+)/$',
            CategoryView.as_view(), name='category-detail-view'),
]

vmaig_blog/urls.py
from django.conf.urls import include, url
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap, Sitemap
from django.core.urlresolvers import reverse

from django.contrib import admin

from blog.models import Article, News, Category, Column


class StaticViewSitemap(Sitemap):
    priority = 1.0
    changefreq = 'daily'

    def items(self):
        return ['index-view', 'news-view']

    def location(self, item):
        return reverse(item)

sitemaps = {
    'article-is-top': GenericSitemap(
                {
                    'queryset': Article.objects.filter(
                                    status=0, is_top=True
                                ).all(),
                    'date_field': 'pub_time'
                },
                priority=1.0,
                changefreq='daily'
            ),
    'article-is-not-top': GenericSitemap(
                {
                    'queryset': Article.objects.filter(status=0).all(),
                    'date_field': 'pub_time'
                },
                priority=0.8,
                changefreq='daily'
            ),
    'news': GenericSitemap(
                {
                    'queryset': News.objects.all(),
                    'data_field': 'pub_time'
                },
                priority=0.6,
                changefreq='daily'
            ),
    'category': GenericSitemap(
                {
                    'queryset': Category.objects.all()
                },
                priority=0.9,
                changefreq='daily'
            ),
    'column': GenericSitemap(
                {
                    'queryset': Column.objects.all()
                },
                priority=0.9,
                changefreq='daily'
            ),
    'static': StaticViewSitemap
}


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blog.urls')),
    url(r'', include('vmaig_comments.urls')),
    url(r'', include('vmaig_auth.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings


class string_with_title(str):
    """ 用来修改admin中显示的app名称,因为admin app 名称是用 str.title()显示的,
    所以修改str类的title方法就可以实现.
    """
    def __new__(cls, value, title):
        instance = str.__new__(cls, value)
        instance._title = title
        return instance

    def title(self):
        return self._title

    __copy__ = lambda self: self
    __deepcopy__ = lambda self, memodict: self

# Create your models here.
STATUS = {
        0: u'正常',
        1: u'草稿',
        2: u'删除',
}

# 资讯来源
NEWS = {
        0: u'oschina',
        1: u'chiphell',
        2: u'freebuf',
        3: u'cnBeta',
}


class Nav(models.Model):
    name = models.CharField(max_length=40, verbose_name=u'导航条内容')
    url = models.CharField(max_length=200, blank=True, null=True,
                           verbose_name=u'指向地址')

    status = models.IntegerField(default=0, choices=STATUS.items(),
                                 verbose_name=u'状态')
    create_time = models.DateTimeField(u'创建时间', auto_now_add=True)

    class Meta:
        verbose_name_plural = verbose_name = u"导航条"
        ordering = ['-create_time']
        app_label = string_with_title('blog', u"博客管理")

    def __unicode__(self):
        return self.name

    __str__ = __unicode__


class Category(models.Model):
    name = models.CharField(max_length=40, verbose_name=u'名称')
    parent = models.ForeignKey('self', default=None, blank=True, null=True,
                               verbose_name=u'上级分类')
    rank = models.IntegerField(default=0, verbose_name=u'排序')
    status = models.IntegerField(default=0, choices=STATUS.items(),
                                 verbose_name=u'状态')

    create_time = models.DateTimeField(u'创建时间', auto_now_add=True)

    class Meta:
        verbose_name_plural = verbose_name = u'分类'
        ordering = ['rank', '-create_time']
        app_label = string_with_title('blog', u"博客管理")

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('category-detail-view', args=(self.name,))

    def __unicode__(self):
        if self.parent:
            return '%s-->%s' % (self.parent, self.name)
        else:
            return '%s' % (self.name)

    __str__ = __unicode__


class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=u'作者')
    category = models.ForeignKey(Category, verbose_name=u'分类')
    title = models.CharField(max_length=100, verbose_name=u'标题')
    en_title = models.CharField(max_length=100, verbose_name=u'英文标题')
    img = models.CharField(max_length=200,
                           default='/static/img/article/default.jpg')
    tags = models.CharField(max_length=200, null=True, blank=True,
                            verbose_name=u'标签', help_text=u'用逗号分隔')
    summary = models.TextField(verbose_name=u'摘要')
    content = models.TextField(verbose_name=u'正文')
    view_times = models.IntegerField(default=0)
    zan_times = models.IntegerField(default=0)

    is_top = models.BooleanField(default=False, verbose_name=u'置顶')
    rank = models.IntegerField(default=0, verbose_name=u'排序')
    status = models.IntegerField(default=0, choices=STATUS.items(),
                                 verbose_name='状态')
    pub_time = models.DateTimeField(default=False, verbose_name=u'发布时间')
    create_time = models.DateTimeField(u'创建时间', auto_now_add=True)
    update_time = models.DateTimeField(u'更新时间', auto_now=True)

    def get_tags(self):
        tags_list = self.tags.split(',')
        while '' in tags_list:
            tags_list.remove('')

        return tags_list

    class Meta:
        verbose_name_plural = verbose_name = u'文章'
        ordering = ['rank', '-is_top', '-pub_time', '-create_time']
        app_label = string_with_title('blog', u"博客管理")

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('article-detail-view', args=(self.en_title,))

    def __unicode__(self):
            return self.title

    __str__ = __unicode__


class Column(models.Model):
    name = models.CharField(max_length=40, verbose_name=u'专栏内容')
    summary = models.TextField(verbose_name=u'专栏摘要')
    article = models.ManyToManyField(Article, verbose_name=u'文章')
    status = models.IntegerField(default=0, choices=STATUS.items(),
                                 verbose_name='状态')
    create_time = models.DateTimeField(u'创建时间',
                                       auto_now_add=True)

    class Meta:
        verbose_name_plural = verbose_name = u'专栏'
        ordering = ['-create_time']
        app_label = string_with_title('blog', u"博客管理")

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('column-detail-view', args=(self.name,))

    def __unicode__(self):
        return self.name

    __str__ = __unicode__


class Carousel(models.Model):
    title = models.CharField(max_length=100, verbose_name=u'标题')
    summary = models.TextField(blank=True, null=True, verbose_name=u'摘要')
    img = models.CharField(max_length=200, verbose_name=u'轮播图片',
                           default='/static/img/carousel/default.jpg')
    article = models.ForeignKey(Article, verbose_name=u'文章')
    create_time = models.DateTimeField(u'创建时间', auto_now_add=True)

    class Meta:
        verbose_name_plural = verbose_name = u'轮播'
        ordering = ['-create_time']
        app_label = string_with_title('blog', u"博客管理")


class News(models.Model):
    title = models.CharField(max_length=100, verbose_name=u'标题')
    summary = models.TextField(verbose_name=u'摘要')
    news_from = models.IntegerField(default=0, choices=NEWS.items(),
                                    verbose_name='来源')
    url = models.CharField(max_length=200, verbose_name=u'源地址')
    create_time = models.DateTimeField(u'创建时间', auto_now_add=True)
    pub_time = models.DateTimeField(default=False, verbose_name=u'发布时间')

    class Meta:
        verbose_name_plural = verbose_name = u'资讯'
        ordering = ['-title']
        app_label = string_with_title('blog', u"博客管理")

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('news-detail-view', args=(self.pk,))

    def __unicode__(self):
        return self.title

    __str__ = __unicode__

templates/blog/all.html
{% extends "blog/base.html" %}

{% block main%}
<div class="row">
    <div id="vmaig-content" class="col-md-8 col-lg-9">
        <div id="tool" class="well clearfix">
            <div class="tags">
                <div class="tag-list" style="float:left">
                    <label class="active">
                        全部
                        <input type="radio" name="category" value="all" style="display:none"></input>
                    </label>
                    {% for category in category_list%}
                    <label>
                        {{category.name}}
                        <input type="radio" name="category" value="{{category.name}}" style="display:none"></input>
                    </label>
                    {% endfor%}
                </div>
            </div>
        </div>

        <div class="well">
            <div class="sort">
                <label>
                    <input type="radio" name="sort" value="time" checked="checked"> 按时间排序
                </label>
                <label>
                    <input type="radio" name="sort" value="recommend"> 按热度排序
                </label>
                <label>
                    <input type="radio" name="sort" value="comment"> 按评论排序
                </label>
            </div>

            <div id="all-post-list">
                {% if article_list %}
                {% with post_list=article_list %}
                {% for post in post_list %} 
                    {% include "blog/include/all_post.html"%}
                {% endfor %}
                {% endwith %}
                {% endif %}
            </div>
            <div id="loading" style="height:100px;line-height:100px;text-align:center;display:none;">
                <img src="http://vmaig.qiniudn.com/loading.gif" alt="">
            </div>


        </div>
        <button id="all-post-more" type="button" class="btn btn-vmaig" value="all" style="width:100%">
            加载更多
            <span class="glyphicon glyphicon-menu-down"></span>
        </button>

    </div>

    <div id="vmaig-side" class="col-md-4 col-lg-3 hidden-xs">
        {% include "blog/widgets/tags_cloud.html"%}
        {% include "blog/widgets/search.html"%}
        {% include "blog/widgets/hotest_posts.html"%}
        {% include "vmaig_comments/latest_comments.html"%}
    </div>
</div>

{% endblock %}

{% block js%}
<script language="javascript" type="text/javascript">

    var start = 0;
    var end = parseInt({{PAGE_NUM}});

    $("input[name='category']").click(function(){
        start = 0;
        end = parseInt({{PAGE_NUM}});
        $("input[name='category']").parent().removeClass("active");
        $("#all-post-more")[0].style.display = "none";
        $("#loading")[0].style.display = "block";

        $("#all-post-list").empty();
        $(this).parent().addClass("active");
        $("#all-post-more").val($(this).val());
        $.ajax({
            type:"POST",
            url:"/all/",
            data:{"val":$(this).attr("value"),"sort":$("input[name='sort']:checked").val(),"start":start,"end":end},
            beforeSend:function(xhr){
                xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'));  
            },
            success:function(data,textStatus){
                $("#loading")[0].style.display = "none";
                $('#all-post-list').append(data["html"]);
                if(data["isend"])
                {
                    $("#all-post-more")[0].style.display = "none";
                }else{
                    $("#all-post-more")[0].style.display = "block";
                }
            },
            error:function(XMLHttpRequest, textStatus, errorThrown){
                alert(XMLHttpRequest.responseText);

            }
        });
    });

    $("input[name='sort']").click(function(){
        start = 0;
        end = parseInt({{PAGE_NUM}});
        $("#all-post-more")[0].style.display = "none";
        $("#loading")[0].style.display = "block";

        $("#all-post-list").empty();
        $.ajax({
            type:"POST",
            url:"/all/",
            data:{"val":$("label.active input").val(),"sort":$("input[name='sort']:checked").val(),"start":start,"end":end},
            beforeSend:function(xhr){
                xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'));  
            },
            success:function(data,textStatus){
                $("#loading")[0].style.display = "none";
                $('#all-post-list').append(data["html"]);
                if(data["isend"])
                {
                    $("#all-post-more")[0].style.display = "none";
                }else{
                    $("#all-post-more")[0].style.display = "block";
                }
            },
            error:function(XMLHttpRequest, textStatus, errorThrown){
                alert(XMLHttpRequest.responseText);
            }
        });

    });

    

    $("#all-post-more").click(function(){
        start = end;
        end += 5;
        $("#loading")[0].style.display = "block";
        $.ajax({
            type:"POST",
            url:"/all/",
            data:{"val":$(this).attr("value"),"sort":$("input[name='sort']:checked").val(),"start":start,"end":end},
            beforeSend:function(xhr){
                xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'));  
            },
            success:function(data,textStatus){
                $("#loading")[0].style.display = "none";
                $("#all-post-more")[0].style.display = "none";
                $('#all-post-list').append(data["html"]);

                if(data["isend"])
                {
                    $("#all-post-more")[0].style.display = "none";
                }else{
                    $("#all-post-more")[0].style.display = "block";
                }

            },
            error:function(XMLHttpRequest, textStatus, errorThrown){
                alert(XMLHttpRequest.responseText);
            }
        });
    });

</script>
{% endblock%}

templates/blog/article.html
{% extends "blog/base.html" %}

{% block main %}

{% url 'category-detail-view' article.category.name as category_url %}

<div class="row">
    <div id="vmaig-content" class="col-md-8 col-lg-9">
        <div id="article-page" class="well">
            <ol class="breadcrumb">
                <li><a href="/"><span class="glyphicon glyphicon-home"></span></a></li>
                <li><a href="{{category_url}}">{{article.category}}</a></li>
                <li class="hidden-xs"><a><span class="glyphicon glyphicon-calendar"></span> {{article.pub_time|date:"Y-m-d"}}</a></li>
                <li><a>
                    <span class="glyphicon glyphicon-eye-open"></span>
                    {{article.view_times}}
                </a></li>
                <li class="pull-right"><a>
                    <span class="glyphicon glyphicon-user"></span> {{article.author}}
                </a></li>
            </ol>

            <div id="article">
                <div class="article-title">
                    <h1>{{article.title}}</h1>
                </div>
                <div class="article-tags">
                    {% for tag in article.get_tags%}
                    <a href="{% url 'tag-detail-view' tag %}">
                        <span class="label label-vmaig-{{forloop.counter}} btn">{{tag}}</span>
                    </a>
                    {% endfor %}
                </div>
                <hr/>
                <div class="article-content">
                    {% autoescape off%}
                    {{article.content}}
                    {% endautoescape %}
                </div>
            </div>
        </div>

        <!--评论框 -->
        {% include "vmaig_comments/vmaig_comments.html"%}

    </div>

    <div id="vmaig-side" class="col-md-4 col-lg-3 hidden-xs">

        {% include "blog/widgets/tags_cloud.html"%}
        {% include "blog/widgets/search.html"%}
        {% include "blog/widgets/hotest_posts.html"%}
        {% include "vmaig_comments/latest_comments.html"%}
    </div>
</div>
{% endblock %}

{% block css%}
<link type="text/css" rel="stylesheet" href="/static/syntaxhighlighter/styles/shCoreDefault.css"/>
<style type="text/css">
    #article {
        font-size:14px;
        color:#000;
    }

    blockquote {
        font-size:14px;
    }
</style>
{% endblock %}


{% block js%}
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shCore.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushCpp.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushJava.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushPython.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushXml.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushPowerShell.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushJScript.js"></script>
<script type="text/javascript">SyntaxHighlighter.all();</script>
{% endblock%}

templates/blog/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <!--手机html -->
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0" />
    <title>{{website_title}}</title>
    <link rel="shortcut icon" href="/static/img/favicon.ico"/>
    <link rel="bookmark" href="/static/img/favicon.ico"/>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/vmaig.css">
    <link rel="stylesheet" href="/static/css/vmaig_comments.css">
    <link rel="stylesheet" href="/static/css/vmaig_auth.css">
    <link rel="stylesheet" href="/static/jquery/jquery.Jcrop.min.css">

    <script src="/static/jquery/jquery-2.1.3.min.js"></script>
    <script src="/static/jquery/jquery.cookie.js"></script>
    <script src="/static/jquery/jquery.form.js"></script>
    <script src="/static/jquery/jquery.Jcrop.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>

    {% block css%} {% endblock%}
</head>
<body id="vmaig">
    <!-- 导航栏 -->
    {% include "blog/include/nav.html"%}
    <!-- 文章列表 与 侧边的东西 -->
    <div id="vmaig-main">
        <div id="vmaig-content" class="container">
            {%block main%} {% endblock %}
        </div>
        <footer>
           <div class="container">
               <p class="text-center">基于Dajngo1.8,Bootsratp3,
{#                   <a href="/sitemap.xml">网站地图</a>#}
               </p>
           </div>
        </footer>
    </div>

</body>


<script type="text/javascript" src="/static/js/vmaig.js"></script>
{% block js%}{% endblock%}

</html>

templates/blog/category.html
{% extends "blog/base.html"%}

{% block main%}
<div class="row">
    <div id="vmaig-content" class="col-md-8 col-lg-9">
        <div id="all-post-list" class="well">
            {% if article_list %}
            {% with post_list=article_list %}
            {% for post in post_list %} 
                {% include "blog/include/category_post.html"%}
            {% endfor %}
            {% endwith %}
            {% endif %}
        </div>
        
        <!--分页 -->
        {% if page_obj%}
        {% include "blog/include/pagination.html"%}
        {% endif %}
    </div>
    <div id="vmaig-side" class="col-md-4 col-lg-3 hidden-xs">
        {% include "blog/widgets/tags_cloud.html"%}
        {% include "blog/widgets/search.html"%}
        {% include "blog/widgets/hotest_posts.html"%}
        {% include "vmaig_comments/latest_comments.html"%}
    </div>
</div>
{% endblock %}

templates/blog/forgetpassword.html
{% extends "blog/base.html"%}

{% block main %}
    {% include "vmaig_auth/forgetpassword.html"%}
{% endblock%}

templates/blog/index.html
{% extends "blog/base.html" %}

{%block main%}
<div class="row">
    <div id="vmaig-content" class="col-md-8 col-lg-9">
        <!-- 警告框 -->
        <div class="well alert hidden-xs fade in">
            <button class="close" data-dismiss="alert" type="button">&times;</button>
            {{website_welcome}}
        </div>

        <div class="visible-xs">
            <div class="search">
                <form class="form-inline clearfix" role="form" method="get" action="/search/"> 
                    <input type="text" class="form-control" id="top-s" name="s">
                    <button class="btn btn-info">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </form>
            </div>
        </div>
        <!-- 首页文章列表 -->
        <div id="home-post-list">
            <!-- 首页轮播 -->
            {% if carousel_page_list%}
            {% include "blog/include/carousel.html"%}
            {% endif%}

            <!--首页文章列表 -->
            {% if article_list %}
            {% with post_list=article_list %}
            {% for post in post_list %}
                {% include "blog/include/home_post.html" %}
            {% endfor %}
            {% endwith %}
            {% endif %}

            <!--分页 -->
            {% if page_obj%}
            {% include "blog/include/pagination.html"%}
            {% endif %}
        </div>
    </div>

    <!-- 右边的widgets -->
    <div id="vmaig-side" class="col-md-4 col-lg-3 hidden-xs">
        {% include "blog/widgets/tags_cloud.html"%}
        {% include "blog/widgets/search.html"%}
        {% include "blog/widgets/hotest_posts.html"%}
        {% include "vmaig_comments/latest_comments.html"%}
        {% include "blog/widgets/links.html"%}
    </div>
</div>
{% endblock %}

templates/blog/login.html
{% extends "blog/base.html"%}

{% block main %}
    {% include "vmaig_auth/login.html"%}
{% endblock%}

templates/blog/news.html
{% extends "blog/base.html" %}

{% block main %}

<div class="timeline-content visible-xs">
    <span>新闻来源：</span>
    
    <span class="label label-success">oschina</span>
    <span class="label label-danger">chiphell</span>
    <span class="label label-primary">cnBeta</span>
    <span class="label label-warning">freebuf</span>
    <span class="label label-default">其他</span>

</div>
<ul class="timeline">
    {% for timeblock in timeblocks%}
    <li>
        <div class="timeline-time">
            {% if forloop.first %}
            <div class="pull-right hidden-xs">
                <span>新闻来源：</span>
                
                <span class="label label-success">oschina</span>
                <span class="label label-danger">chiphell</span>
                <span class="label label-primary">cnBeta</span>
                <span class="label label-warning">freebuf</span>
                <span class="label label-default">其他</span>
            </div>
            {% endif %}

            <span>{{timeblock.0.pub_time|date:"D d M Y"}}</span>

        </div>
        <div class="timeline-ico"></div>
        <div class="timeline-content">

            {% for news in timeblock%}
            <a class="label label-{{news.get_news_from_display}} label-news " onclick="return hs.htmlExpand(this, { objectType: 'iframe' ,minWidth:600,headingText:'{{news.title}}'})" href="{% url 'news-detail-view' news.pk  %}">{{news.title}}</a>
            {% endfor %}

        </div>
    </li>
    {% endfor%}
</ul>

<div class="timeline-select hidden-xs">
    <ul class="list-group">
        <li class="list-group-item {% if active == 0 %}active{% endif %}"><a href="/news/?start=0&end=6">最近7天</a></li>
        <li class="list-group-item {% if active == 1 %}active{% endif %}"><a href="/news/?start=7&end=13">前一周</a></li>
        <li class="list-group-item {% if active == 2 %}active{% endif %}"><a href="/news/?start=14&end=20">前二周</a></li>
        <li class="list-group-item {% if active == 3 %}active{% endif %}"><a href="/news/?start=21&end=27">前三周</a></li>
        <li class="list-group-item {% if active == 4 %}active{% endif %}"><a href="/news/?start=28&end=34">前四周</a></li>
        <li class="list-group-item {% if active == 5 %}active{% endif %}"><a href="/news/?start=35&end=41">前五周</a></li>
    </ul>
</div>

{% endblock %}

{% block js%}

<script src="/static/highslide/highslide-with-html.min.js"></script> 
<script language="javascript" type="text/javascript">
    hs.graphicsDir = '/static/highslide/graphics/';
    hs.outlineType = 'rounded-white';
    hs.showCredits = false;
    hs.wrapperClassName = 'draggable-header';
    hs.marginTop = 70;

</script>

{% endblock%}


{% block css%}

<link rel="stylesheet" href="/static/highslide/highslide.css">
<style type="text/css">

    /*手机端控制弹出框宽度*/
    @media screen and (max-width: 400px) {
        .highslide-body {
            width:320px !important;
        }

        ..highslide-html {
            width:320px !important;
        }

        .highslide-html-content{
            width:325px !important;
        }

        .highslide-html-blur{
            width:320px !important;
        }
    }

    .highslide-header  {
        height:30px !important;
    }
    .highslide-heading {
        font-size:18px !important;

        max-width: 90%;
        white-space: nowrap;
        text-overflow: ellipsis;
        display: inline-block!important;
        overflow: hidden;
    }

    .timeline {
        list-style: none;
        position: relative;
    }


    .timeline:before{
        content: '';
        position: absolute;
        top: 0;
        bottom: 0;
        width: 6px;
        background: #D94600;
        left: 10%;
    }

    .timeline li{
        position: relative;
    }

    .timeline-time {
        margin-left:10%;
        margin-bottom:10px;
    }

    .timeline-time>span:last-child {
        font-size: 18px;
        color: #FFFF00;
        font-weight: bold;
    }

    .timeline-time div {
        font-size:16px;
    }

    .timeline-time div span:first-child {
        font-size: 18px;
        color: #FFFF00;
        font-weight: bold;

    }

    .timeline-ico {
        width: 10px;
        height: 10px;
        speak: none;
        font-style: normal;
        font-weight: normal;
        font-variant: normal;
        text-transform: none;
        font-size: 1.4em;
        line-height: 40px;
        position: absolute;
        color: #fff;
        background: #eee;
        border-radius: 50%;
        box-shadow: 0 0 0 8px #D94600;
        text-align: center;
        left: 10%;
        top: 0;
        margin: 0 0 0 -38px;
    }

    .timeline-content {
        margin: 0 0 15px 10%;
        background-color: rgba(0,0,0,0.6);
        padding:10px;
    }

    .label-news{
        display:inline-block;
        font-size:14px;
        max-width:100%;
        margin:3px;
        white-space: nowrap;
        text-overflow: ellipsis;
        display: inline-block;
        overflow: hidden;

    }

    .timeline-select {
        position: fixed;
        top:70px;
        left:20px;
    }

    .label-oschina {
        background-color: #5cb85c;
    }

    .label-chiphell {
        background-color: #d9534f;
    }

    .label-cnBeta {
        background-color: #337ab7;
    }

    .label-freebuf {
        background-color: #f0ad4e;
    }

</style>

{% endblock %}

templates/blog/news_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" /> 
    <title></title>
    <style type="text/css">
        img {
            width:95%;
        }
    </style>
</head>
<body>
{% autoescape off%}
{{news.summary}}
{% endautoescape %}
   
</body>
</html>

templates/blog/register.html
{% extends "blog/base.html"%}

{% block main %}
    {% include "vmaig_auth/register.html"%}
{% endblock%}

templates/blog/resetpassword.html
{% extends "blog/base.html"%}

{% block main %}
    {% include "vmaig_auth/resetpassword.html"%}
{% endblock%}